team_mapping = {
    "DC Utd": "DC United",
    "Minnesota Utd": "Minnesota United",
    "Nashville SC": "Nashville SC",
    "HOU Dynamo": "Houston Dynamo",
    "Real Salt Lake": "Real Salt Lake",
    "LAFC": "Los Angeles FC",
    "CHI Fire": "Chicago Fire",
    "Vancouver Whitecaps": "Vancouver Whitecaps",
    "Inter Miami": "Inter Miami",
    "St Louis City SC": "St. Louis City SC",
    "Austin FC": "Austin FC",
    "FC Cincinnati": "FC Cincinnati",
    "Charlotte FC": "Charlotte FC",
    "Seattle Sounders": "Seattle Sounders",
    "New York Red Bulls": "New York Red Bulls",
    "Atlanta Utd": "Atlanta United",
    "CF Montreal": "CF Montréal",
    "Orlando City": "Orlando City",
    "Toronto FC": "Toronto FC",
    "NE Revolution": "New England Revolution",
    "PHI Union": "Philadelphia Union",
    "FC Dallas": "FC Dallas",
    "COL Rapids": "Colorado Rapids",
    "SJ Earthquakes": "San Jose Earthquakes",
}